### ISSUE TITLE
Setup publishing

### ISSUE THREAD

**Issue by kidrecursive** [stargate/stargate-mongoose#1]
Setup NPM publishing for the stargate-mongoose package.

**Comment by amorton** [comment]
In meeting: We will publish to NPM similar to https://www.npmjs.com/package/@astrajs/collections and call `stargate-mongoose` under `@astrajs`

for the readme - add some examples into the quick start section, and confirm the code examples work

and make these samples work https://github.com/meanIT/mongoose-astra-sample-apps
