### ISSUE TITLE
Remove env variables in the main flow

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#10]
When the driver makes a call to the backend server, it sends the authorization token in a header field called 'X-Cassandra-Token' by default. In order to override this header name when needed, there is an environment variable used, which is called 'AUTH_HEADER_NAME'. This needs to be changed to be a client option while creating the connection, instead of an environment variable, since this driver doesn't rely on any environment variable for any functionality apart from some test flows and we don't want to introduce this just for this requirement.

**Comment by vkarpov15** [comment]
Agreed. In general, npm libs should not rely on environment variables for configuration for numerous reasons. A couple of examples: environment variables aren't typed for TypeScript and don't autocomplete well. And environment variables are singletons, which makes it difficult to create two clients that use two different auth headers in the same process.
