### ISSUE TITLE
stargate-mongoose performance testing

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#100]

**Comment by jeffreyscarpenter** [comment]
@amorton / @kathirsvn can you add some description?

**Comment by jeffreyscarpenter** [comment]
@vkarpov15 Are there existing performance tests for Mongoose that we could leverage? Or feel free to add other recommendations on approach. 

The basic goal is to validate that our driver isn't adding a lot of overhead on top of the underlying API.

**Comment by vkarpov15** [comment]
@jeffreyscarpenter Mongoose's benchmarks are fairly minimal: https://github.com/Automattic/mongoose/blob/master/benchmarks/mapOfSubdocs.js . We haven't prioritized building out a suite of benchmarks yet.

**Comment by jeffreyscarpenter** [comment]
@vkarpov15 do you want to add links to the tests you performed? We can probably close this ticket after that.

**Comment by vkarpov15** [comment]
Sure, here's the github gist containing source files and results: https://gist.github.com/vkarpov15/70b4a87b4d2d369699ddf04f202547ab
