### ISSUE TITLE
Flexible enforcement for not implemented functionality

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate-mongoose#108]
Stargate-mongoose does not implement some operations supported by Mongoose JS. The current implementation of stargate-mongoose throws an error for these operations with the message "Not implemented". We should make this behavior configurable so that there is an option to just implement these operations as noops (with logging?) instead of the not implemented error. This will make it easier for existing mongoose apps to run with stargate-mongoose.

**Comment by tatu-at-datastax** [comment]
One potential challenge: operations typically require specific response information for successful execution (like `_id` of document inserted/updated). So it is possible that only some commands can be implemented. Perhaps this just means that the first task here is investigating which commands can be implemented as no-ops (and to which degree) and which can not.

Logging may already "just work" in the sense that we produce metrics for endpoints, along with tagging to indicate command.
