### ISSUE TITLE
Support $vector in replacement operator

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#121]
As per comments from vkarpov15 here, `replacement` operator can not take `$vector` field currently.

https://github.com/stargate/stargate-mongoose/pull/120#issuecomment-1657215854

> Currently cannot use findOneAndReplace() with $vector in replacement. Mongoose throws error The replacement document must not contain atomic operators. because it assumes that any fields that start with $ are update operators. I'll look into this.

**Comment by vkarpov15** [comment]
Should be fixed by #128
