### ISSUE TITLE
Confirm use of HTTP 2

### ISSUE THREAD

**Issue by amorton** [stargate/stargate-mongoose#152]
We want to be on HTTP 2 for performance etc. 

Looks like axios still does not support it https://github.com/axios/axios/issues/1175

@vkarpov15  can you pls look into if we need to change, what the best alternative is, and make the change ? 

@alexleventer  can you pls take a look at this to make sure the typescript client is also doing this (cannot remember how we ended with typescript driver using the exact same code)

**Comment by vkarpov15** [comment]
Related PR: https://github.com/stargate/stargate-mongoose/pull/153. Sorry, did not see this issue before putting in that PR.

**Comment by jeffreyscarpenter** [comment]
fixed by #153
