### ISSUE TITLE
findOne with Object Id with toString filter fails

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#219]
The following currently fails where the `insertedId` is of type `ObjectId` :

```typescript
const doc = await db.collection(collectionName).findOne({ _id: insertedId.toString() });
```

More context here: https://github.com/stargate/stargate-mongoose/pull/214/files#diff-4405e0935552ddb1ffac14d14f5d399dec7b7094df2d7a1810414d5f6685568bR199

cc: @vkarpov15

**Comment by vkarpov15** [comment]
@kathirsvn I opened up issue for this here: https://github.com/stargate/data-api/issues/1045. Looks like it is expected behavior in data-api. I'll put in PR to remove this test.
