### ISSUE TITLE
Buffering for `createCollection` and `dropCollection()`

### ISSUE THREAD

**Issue by vkarpov15** [stargate/stargate-mongoose#29]
Right now, if you call `Connection.prototype.createCollection()` in the driver layer before calling `openUri()`, you'll get a "Cannot read property `db` of undefined" here: https://github.com/stargate/stargate-mongoose/blob/cd66b63bd9042b6e7b8f70626de3d7dab7e6534f/src/driver/connection.ts#L35

Mongoose unfortunately relies on this behavior: when you call `mongoose.model()`, that makes Mongoose call `Model.init()`, which calls `createCollection()` by default. This is why I had to disable `autoCreate` and `autoIndex` here: https://github.com/meanIT/mongoose-astra-sample-apps/commit/2085069107d926fb8be2ec51df5789a8796df565#diff-e5cca2ae504d457cacda76ef11ce3b6c53c9222701d38f080b9c1b2fc2ce8562 . This is why Mongoose has this [`wrapConnHelper()` function](https://github.com/Automattic/mongoose/blob/2b946976d73d66263492d4f30c3eabfe35b35968/lib/connection.js#L400).

Not a blocker for initial release, but we should make a note to recommend disabling `autoCreate` and `autoIndex` for now until we support this. Otherwise you end up with collections not being created by default, and no way to diagnose why.

**Comment by kidrecursive** [comment]
Yep, let's support this.
