### ISSUE TITLE
Confirm behavior when collection created but not active, impacts testing

### ISSUE THREAD

**Issue by amorton** [stargate/stargate-mongoose#30]
From meeting 24 August. 

May involve how we create collection automatically.

**Comment by ivansenic** [comment]
Can I get some context here?

**Comment by amorton** [comment]
@ivansenic @kidrecursive  was looking at how to reproduce, there is a delay between the collection being created and being available and we were hitting that. 

@kidrecursive  any updates ?

**Comment by ivansenic** [comment]
Yes, OSS Cassandra has that issue, creating collection takes some time (table creation, indexes, schema change wait).. It even fails if two threads do it in parallel (fails on one thread).. DSE is not having that issue, thus on Astra this should be fine.

**Comment by kidrecursive** [comment]
This should be mitigated now that @vkarpov15 added buffering for collection operatoins.
