### ISSUE TITLE
Stargate v2: Allow accessing document function API without specifying a document path

### ISSUE THREAD

**Issue by vkarpov15** [stargate/stargate-mongoose#35]
Right now, `POST http://127.0.0.2:8180/v2/namespaces/test/collections/users/631fab0cf717e9e52959ac2c/function` returns an `HTTP 405 Method Not Allowed`. You need to specify a document path, because according to Eric B the Stargate API's endpoint is configured as follows:

```
POST /v2/namespaces/:namespace/collections/{collection:\\w+}/{document-id}/{document-path:.*}/function
```

This unfortunately means that we can't `$set` multiple top-level paths. For example, suppose we have the following document:

```
{
  name: {
    first: 'Val',
    last: 'Karpov'
  },
  languages: ['JavaScript', 'TypeScript']
}
```

There would be no way to send a single API request that would `$set` both `name.first` _and_ `languages.[0]`. I would need to send a separate `POST /v2/namespaces/test/collections/users/631fab0cf717e9e52959ac2c/name/function` and a separate `POST /v2/namespaces/test/collections/users/631fab0cf717e9e52959ac2c/languages/function`

**Comment by EricBorczuk** [comment]
This should be resolved by https://github.com/stargate/stargate/pull/2067, which allows $set on the root of the document

**Comment by ivansenic** [comment]
Done in #2067.
