### ISSUE TITLE
Auto update Stargate-mongoose in the Sample apps repo

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#57]
Update stargate-mongoose release workflow to create a PR that bumps the stargate-mongoose version in stargate-mongoose-sample-apps

**Comment by vkarpov15** [comment]
@kathirsvn is there any way we can just enable dependabot in stargate-mongoose-sample-apps? I think that would be sufficient to solve this issue without us needing to implement a custom workflow, but it looks like I don't have permission to do so.

![image](https://github.com/stargate/stargate-mongoose/assets/1620265/b122171f-46b8-4bee-a7af-8e77e377ca7a)

I once [wrote a GitHub app that handled syncing package.json dependencies](https://github.com/vkarpov15/pkgsync/blob/master/api/actions/sync.js), so I can tell you from firsthand experience that writing custom code for creating GitHub PRs is difficult :)

**Comment by kathirsvn** [comment]
@vkarpov15 SGTM. I enabled the same and added the dependabot.yml in [this PR](https://github.com/stargate/stargate-mongoose-sample-apps/pull/29) Please review when you get a chance.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/stargate/stargate-mongoose-sample-apps/pull/29
