### ISSUE TITLE
batchSize for FindCursor

### ISSUE THREAD

**Issue by vkarpov15** [stargate/stargate-mongoose#83]
[Mongoose uses cursors to avoid loading the entire result set into memory at once](https://thecodebarbarian.com/cursors-in-mongoose-45), but right now `FindCursor` always loads the entire result set into memory.

An additional related issue is that jsonapi doesn't support paging with sort, `data.nextPageState` is always `null` with `sort` even if there's more docs, which is something we'll need to think about. if we ignore sort, it is fairly easy to implement a default batch size, but sort makes it tricky.

This issue is more for GA, we don't need it for private preview.

**Comment by jeffreyscarpenter** [comment]
@kathirsvn I don't recall reopening this, should it be closed?

**Comment by vkarpov15** [comment]
@jeffreyscarpenter I think this should stay open, we fixed part of this with #117 but the original issue remains unresolved.

**Comment by vkarpov15** [comment]
@jeffreyscarpenter I took a closer look and we can close this issue. #144 demonstrates that OP is no longer an issue.
