### ISSUE TITLE
Mongoose API level tests

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#97]
Add tests covering all the Mongoose level APIs, Data types and options as much as possible.

Connection level options

* strict
* strictQuery
* autoIndex
* autoCreate

Data types

* [String](https://mongoosejs.com/docs/schematypes.html#strings)
* [Number](https://mongoosejs.com/docs/schematypes.html#numbers)
* [Date](https://mongoosejs.com/docs/schematypes.html#dates)
* [Buffer](https://mongoosejs.com/docs/schematypes.html#buffers)
* [Boolean](https://mongoosejs.com/docs/schematypes.html#booleans)
* [Mixed](https://mongoosejs.com/docs/schematypes.html#mixed)
* [ObjectId](https://mongoosejs.com/docs/schematypes.html#objectids)
* [Array](https://mongoosejs.com/docs/schematypes.html#arrays)
* [Decimal128](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-Decimal128)
* [Map](https://mongoosejs.com/docs/schematypes.html#maps)
* [Schema](https://mongoosejs.com/docs/schematypes.html#schemas)
* [UUID](https://mongoosejs.com/docs/schematypes.html#uuid)
* [BigInt](https://mongoosejs.com/docs/schematypes.html#bigint)

Model APIs

* [Model()](https://mongoosejs.com/docs/api/model.html#Model())
* [Model.$where()](https://mongoosejs.com/docs/api/model.html#Model.$where())
* [Model.aggregate()](https://mongoosejs.com/docs/api/model.html#Model.aggregate())
* [Model.applyDefaults()](https://mongoosejs.com/docs/api/model.html#Model.applyDefaults())
* [Model.bulkSave()](https://mongoosejs.com/docs/api/model.html#Model.bulkSave())
* [Model.bulkWrite()](https://mongoosejs.com/docs/api/model.html#Model.bulkWrite())
* [Model.castObject()](https://mongoosejs.com/docs/api/model.html#Model.castObject())
* [Model.cleanIndexes()](https://mongoosejs.com/docs/api/model.html#Model.cleanIndexes())
* [Model.count()](https://mongoosejs.com/docs/api/model.html#Model.count())
* [Model.countDocuments()](https://mongoosejs.com/docs/api/model.html#Model.countDocuments())
* [Model.create()](https://mongoosejs.com/docs/api/model.html#Model.create())
* [Model.createCollection()](https://mongoosejs.com/docs/api/model.html#Model.createCollection())
* [Model.createIndexes()](https://mongoosejs.com/docs/api/model.html#Model.createIndexes())
* [Model.db](https://mongoosejs.com/docs/api/model.html#Model.db)
* [Model.deleteMany()](https://mongoosejs.com/docs/api/model.html#Model.deleteMany())
* [Model.deleteOne()](https://mongoosejs.com/docs/api/model.html#Model.deleteOne())
* [Model.diffIndexes()](https://mongoosejs.com/docs/api/model.html#Model.diffIndexes())
* [Model.discriminator()](https://mongoosejs.com/docs/api/model.html#Model.discriminator())
* [Model.distinct()](https://mongoosejs.com/docs/api/model.html#Model.distinct())
* [Model.ensureIndexes()](https://mongoosejs.com/docs/api/model.html#Model.ensureIndexes())
* [Model.estimatedDocumentCount()](https://mongoosejs.com/docs/api/model.html#Model.estimatedDocumentCount())
* [Model.events](https://mongoosejs.com/docs/api/model.html#Model.events)
* [Model.exists()](https://mongoosejs.com/docs/api/model.html#Model.exists())
* [Model.find()](https://mongoosejs.com/docs/api/model.html#Model.find())
* [Model.findById()](https://mongoosejs.com/docs/api/model.html#Model.findById())
* [Model.findByIdAndDelete()](https://mongoosejs.com/docs/api/model.html#Model.findByIdAndDelete())
* [Model.findByIdAndRemove()](https://mongoosejs.com/docs/api/model.html#Model.findByIdAndRemove())
* [Model.findByIdAndUpdate()](https://mongoosejs.com/docs/api/model.html#Model.findByIdAndUpdate())
* [Model.findOne()](https://mongoosejs.com/docs/api/model.html#Model.findOne())
* [Model.findOneAndDelete()](https://mongoosejs.com/docs/api/model.html#Model.findOneAndDelete())
* [Model.findOneAndRemove()](https://mongoosejs.com/docs/api/model.html#Model.findOneAndRemove())
* [Model.findOneAndReplace()](https://mongoosejs.com/docs/api/model.html#Model.findOneAndReplace())
* [Model.findOneAndUpdate()](https://mongoosejs.com/docs/api/model.html#Model.findOneAndUpdate())
* [Model.hydrate()](https://mongoosejs.com/docs/api/model.html#Model.hydrate())
* [Model.init()](https://mongoosejs.com/docs/api/model.html#Model.init())
* [Model.insertMany()](https://mongoosejs.com/docs/api/model.html#Model.insertMany())
* [Model.inspect()](https://mongoosejs.com/docs/api/model.html#Model.inspect())
* [Model.listIndexes()](https://mongoosejs.com/docs/api/model.html#Model.listIndexes())
* [Model.populate()](https://mongoosejs.com/docs/api/model.html#Model.populate())
* [Model.prototype.$model()](https://mongoosejs.com/docs/api/model.html#Model.prototype.$model())
* [Model.prototype.$where](https://mongoosejs.com/docs/api/model.html#Model.prototype.$where)
* [Model.prototype.base](https://mongoosejs.com/docs/api/model.html#Model.prototype.base)
* [Model.prototype.baseModelName](https://mongoosejs.com/docs/api/model.html#Model.prototype.baseModelName)
* [Model.prototype.collection](https://mongoosejs.com/docs/api/model.html#Model.prototype.collection)
* [Model.prototype.collection](https://mongoosejs.com/docs/api/model.html#Model.prototype.collection)
* [Model.prototype.db](https://mongoosejs.com/docs/api/model.html#Model.prototype.db)
* [Model.prototype.deleteOne()](https://mongoosejs.com/docs/api/model.html#Model.prototype.deleteOne())
* [Model.prototype.discriminators](https://mongoosejs.com/docs/api/model.html#Model.prototype.discriminators)
* [Model.prototype.increment()](https://mongoosejs.com/docs/api/model.html#Model.prototype.increment())
* [Model.prototype.model()](https://mongoosejs.com/docs/api/model.html#Model.prototype.model())
* [Model.prototype.modelName](https://mongoosejs.com/docs/api/model.html#Model.prototype.modelName)
* [Model.prototype.save()](https://mongoosejs.com/docs/api/model.html#Model.prototype.save())
* [Model.replaceOne()](https://mongoosejs.com/docs/api/model.html#Model.replaceOne())
* [Model.schema](https://mongoosejs.com/docs/api/model.html#Model.schema)
* [Model.startSession()](https://mongoosejs.com/docs/api/model.html#Model.startSession())
* [Model.syncIndexes()](https://mongoosejs.com/docs/api/model.html#Model.syncIndexes())
* [Model.translateAliases()](https://mongoosejs.com/docs/api/model.html#Model.translateAliases())
* [Model.updateMany()](https://mongoosejs.com/docs/api/model.html#Model.updateMany())
* [Model.updateOne()](https://mongoosejs.com/docs/api/model.html#Model.updateOne())
* [Model.validate()](https://mongoosejs.com/docs/api/model.html#Model.validate())
* [Model.watch()](https://mongoosejs.com/docs/api/model.html#Model.watch())
* [Model.where()](https://mongoosejs.com/docs/api/model.html#Model.where())

For example, tests covering all the examples mentioned in below link.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#overview

**Comment by vkarpov15** [comment]
We'll also have to make some decisions on which cases we error out on, and how we report the errors.

For example, we should report an error on `startSession()`, `watch()`, `bulkWrite()`, or `syncIndexes()`; those are all not supported. We should also consider throwing an error on certain types, like Decimal128 or Buffer, that we don't intend to support.

Maybe we create an `OperationNotSupportedError` class that the driver layer can throw when Mongoose tries to access something that isn't supported.

**Comment by kathirsvn** [comment]
Sure, makes sense. I'll add `OperationNotSupportedError` for any unsupported operations.
